### ISSUE TITLE
Binding pexec to child_process prevents test-stubbing

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [luckydrq/promise-exec#4]
Title basically says it all.

This doesn't work, and there's really no decoupled way around it, when you hard-code `bind`:

```
import pexec from 'promise-exec'
function test_me(something){
   pexec(something)
}

it("won't work", function(){
   sinon.stub(require('child_process'), 'exec')
   test_me('rm -rf /') // Oh-oh, I just wiped my drive!
})
```

I'm not sure what the best way to go about this is, but if you can figure out a way … it's really the only flaw your tiny, but super-effective, library has. >:

**Comment by luckydrq** [comment]
I think the point is not `bind`. It is because `pexec` already hold the reference before `child_process.exec` gets stubbed. Try require `promise-exec` after stub instead of importing it globally:

``` js
it("should work", function() {
   sinon.stub(require('child_process'), 'exec');
   var pexec = require('promise-exec');
   pexec('rm -rf /');
});
```
